config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    pss-gitlab.math.univ-paris-diderot.fr/dralucas/shaltoplib:
      branch: main
      repo: https://pss-gitlab.math.univ-paris-diderot.fr/dralucas/shaltoplib
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      pss-gitlab.math.univ-paris-diderot.fr/dralucas/shaltoplib git:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-persimmon-chameleon.sh
        container: qc.acc_homely-persimmon-moth
  QC.Doc:
    repos:
      pss-gitlab.math.univ-paris-diderot.fr/dralucas/shaltoplib find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.ready-saffron-bandicoot.sh
        container: qc.doc_shabby-pumpkin-russel
      pss-gitlab.math.univ-paris-diderot.fr/dralucas/shaltoplib git:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-goldenrod-tuatara.sh
        container: qc.doc_pokey-teal-gopher
      pss-gitlab.math.univ-paris-diderot.fr/dralucas/shaltoplib markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-orange-goose.sh
        container: qc.doc_pretty-wheat-flounder
  QC.Lic:
    repos:
      pss-gitlab.math.univ-paris-diderot.fr/dralucas/shaltoplib licensee:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-olivine-retriever.sh
        container: qc.lic_lanky-chocolate-scorpion
  QC.Sec:
    repos:
      pss-gitlab.math.univ-paris-diderot.fr/dralucas/shaltoplib bandit:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-teal-cat.sh
        container: qc.sec_pokey-champagne-elephant
  QC.Sty:
    repos:
      pss-gitlab.math.univ-paris-diderot.fr/dralucas/shaltoplib flake8:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-green-swan.sh
        container: qc.sty_goopy-lime-opossum
  QC.Uni:
    repos:
      pss-gitlab.math.univ-paris-diderot.fr/dralucas/shaltoplib pytest:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-indigo-mist.sh
        container: qc.uni_pokey-lemon-coati
  QC.Ver:
    repos:
      pss-gitlab.math.univ-paris-diderot.fr/dralucas/shaltoplib get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-chestnut-tamarin.sh
        container: qc.ver_homey-indigo-seahorse
timeout: 5400
