config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.10
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    pss-gitlab.math.univ-paris-diderot.fr/dralucas/shaltoplib:
      branch: main
      repo: https://pss-gitlab.math.univ-paris-diderot.fr/dralucas/shaltoplib
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      pss-gitlab.math.univ-paris-diderot.fr/dralucas/shaltoplib git:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-corn-booby.sh
        container: qc.acc_snappy-ecru-insect
  QC.Doc:
    repos:
      pss-gitlab.math.univ-paris-diderot.fr/dralucas/shaltoplib find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-olive-lynx.sh
        container: qc.doc_scummy-razzmatazz-cat
      pss-gitlab.math.univ-paris-diderot.fr/dralucas/shaltoplib git:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-thistle-chihuahua.sh
        container: qc.doc_beady-salmon-havanese
      pss-gitlab.math.univ-paris-diderot.fr/dralucas/shaltoplib markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-azure-deer.sh
        container: qc.doc_slimy-red-chimpanzee
  QC.Lic:
    repos:
      pss-gitlab.math.univ-paris-diderot.fr/dralucas/shaltoplib licensee:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-smalt-olm.sh
        container: qc.lic_crabby-blue-tarsier
  QC.Sec:
    repos:
      pss-gitlab.math.univ-paris-diderot.fr/dralucas/shaltoplib bandit:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-cyan-mongrel.sh
        container: qc.sec_frumpy-wheat-lemming
  QC.Sty:
    repos:
      pss-gitlab.math.univ-paris-diderot.fr/dralucas/shaltoplib flake8:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-peach-bandicoot.sh
        container: qc.sty_nerdy-tomato-squirt
  QC.Ver:
    repos:
      pss-gitlab.math.univ-paris-diderot.fr/dralucas/shaltoplib get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-olivine-forest.sh
        container: qc.ver_squirrely-denim-russel
timeout: 5400
