config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    pss-gitlab.math.univ-paris-diderot.fr/dralucas/shaltoplib:
      branch: main
      repo: https://pss-gitlab.math.univ-paris-diderot.fr/dralucas/shaltoplib
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      pss-gitlab.math.univ-paris-diderot.fr/dralucas/shaltoplib git:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-wisteria-bonobo.sh
        container: qc.acc_breezy-saffron-booby
  QC.Doc:
    repos:
      pss-gitlab.math.univ-paris-diderot.fr/dralucas/shaltoplib find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-xanthic-impala.sh
        container: qc.doc_sleazy-alizarin-jackal
      pss-gitlab.math.univ-paris-diderot.fr/dralucas/shaltoplib git:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-asparagus-mongoose.sh
        container: qc.doc_squirrely-red-whippet
      pss-gitlab.math.univ-paris-diderot.fr/dralucas/shaltoplib markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-sangria-blue.sh
        container: qc.doc_snippy-olivine-barracuda
  QC.Lic:
    repos:
      pss-gitlab.math.univ-paris-diderot.fr/dralucas/shaltoplib licensee:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-corn-spoonbill.sh
        container: qc.lic_stinky-amaranth-vole
  QC.Sec:
    repos:
      pss-gitlab.math.univ-paris-diderot.fr/dralucas/shaltoplib bandit:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-bronze-bison.sh
        container: qc.sec_homey-taupe-snake
  QC.Sty:
    repos:
      pss-gitlab.math.univ-paris-diderot.fr/dralucas/shaltoplib flake8:
        commands:
        - /usr/bin/env sh .sqa/script.randy-myrtle-grouse.sh
        container: qc.sty_snippy-thistle-chihuahua
  QC.Uni:
    repos:
      pss-gitlab.math.univ-paris-diderot.fr/dralucas/shaltoplib pytest:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-lime-giraffe.sh
        container: qc.uni_homey-vermilion-alligator
  QC.Ver:
    repos:
      pss-gitlab.math.univ-paris-diderot.fr/dralucas/shaltoplib get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-dandelion-millipede.sh
        container: qc.ver_lanky-violet-reindeer
timeout: 5400
