config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    pss-gitlab.math.univ-paris-diderot.fr/dralucas/shaltoplib:
      branch: main
      repo: https://pss-gitlab.math.univ-paris-diderot.fr/dralucas/shaltoplib
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      pss-gitlab.math.univ-paris-diderot.fr/dralucas/shaltoplib git:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-orange-donkey.sh
        container: qc.acc_clammy-myrtle-malamute
  QC.Doc:
    repos:
      pss-gitlab.math.univ-paris-diderot.fr/dralucas/shaltoplib find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-lemon-burmese.sh
        container: qc.doc_nerdy-periwinkle-raccoon
      pss-gitlab.math.univ-paris-diderot.fr/dralucas/shaltoplib git:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-ecru-lemur.sh
        container: qc.doc_bumpy-olive-ragdoll
      pss-gitlab.math.univ-paris-diderot.fr/dralucas/shaltoplib markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-puce-termite.sh
        container: qc.doc_crappy-cream-dolphin
  QC.Lic:
    repos:
      pss-gitlab.math.univ-paris-diderot.fr/dralucas/shaltoplib licensee:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-chestnut-spitz.sh
        container: qc.lic_snazzy-cobalt-drever
  QC.Sec:
    repos:
      pss-gitlab.math.univ-paris-diderot.fr/dralucas/shaltoplib bandit:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-lavender-gar.sh
        container: qc.sec_scaly-celadon-pig
  QC.Sty:
    repos:
      pss-gitlab.math.univ-paris-diderot.fr/dralucas/shaltoplib flake8:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-orchid-numbat.sh
        container: qc.sty_skinny-champagne-toad
  QC.Uni:
    repos:
      pss-gitlab.math.univ-paris-diderot.fr/dralucas/shaltoplib pytest:
        commands:
        - /usr/bin/env sh .sqa/script.messy-olive-quokka.sh
        container: qc.uni_cheeky-malachite-albatross
  QC.Ver:
    repos:
      pss-gitlab.math.univ-paris-diderot.fr/dralucas/shaltoplib get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-asparagus-bulldog.sh
        container: qc.ver_chewy-black-chinchilla
timeout: 5400
